# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Forward Position Controllers ---------------------------------------
arm_j1_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_1
  pid: {p: 8000.0, i: 100, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j2_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_2
  pid: {p: 8000.0, i: 1000, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j3_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_3
  pid: {p: 8000.0, i: 10, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j4_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_4
  pid: {p: 8000.0, i: 10, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j5_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_5
  pid: {p: 3000.0, i: 5, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j6_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_6
  pid: {p: 500.0, i: 1, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j7_position_controller:
  type: position_controllers/JointPositionController
  joint: iiwa_joint_7
  pid: {p: 100.0, i: 0.1, d: 0.0, i_clamp_min: -10000, i_clamp_max: 10000}

gripper_left_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: gripper_left_joint
  pid: {p: 10.0, i: 0.0, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}

gripper_right_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: gripper_right_joint
  pid: {p: 10.0, i: 0.0, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}

iiwa_position_controller:
  type: position_controllers/JointTrajectoryController
  #type: effort_controllers/JointTrajectoryController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 8000
      d: 0
      i: 100
      i_clamp: 10000
    iiwa_joint_2:
      p: 8000
      d: 0
      i: 1000
      i_clamp: 10000
    iiwa_joint_3:
      p: 8000
      d: 0
      i: 10
      i_clamp: 10000
    iiwa_joint_4:
      p: 8000
      d: 0
      i: 10
      i_clamp: 10000
    iiwa_joint_5:
      p: 3000
      d: 0
      i: 5
      i_clamp: 10000
    iiwa_joint_6:
      p: 500
      d: 0
      i: 1
      i_clamp: 10000
    iiwa_joint_7:
      p: 100
      d: 0
      i: 0.1
      i_clamp: 1
  
# Effort controllers
arm_j1_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_1

arm_j2_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_2

arm_j3_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_3

arm_j4_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_4

arm_j5_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_5

arm_j6_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_6

arm_j7_effort_controllers:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_7

iiwa_effort_controller:
  type: effort_controllers/JointGroupEffortController
  #type: effort_controllers/JointGroupEffortController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 8000
      d: 100
      i: 100
      i_clamp: 10000
    iiwa_joint_2:
      p: 8000
      d: 100
      i: 100
      i_clamp: 10000
    iiwa_joint_3:
      p: 8000
      d: 100
      i: 10
      i_clamp: 10000
    iiwa_joint_4:
      p: 8000
      d: 100
      i: 10
      i_clamp: 10000
    iiwa_joint_5:
      p: 3000
      d: 100
      i: 5
      i_clamp: 10000
    iiwa_joint_6:
      p: 500
      d: 100
      i: 1
      i_clamp: 10000
    iiwa_joint_7:
      p: 100
      d: 100
      i: 1
      i_clamp: 1   
  
grasp_effort_controllers:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_left_joint
    - gripper_right_joint
  gains:
    gripper_left_joint:
      p: 2000
      d: 10
      i: 1
      i_clamp: 10000
    gripper_right_joint:
      p: 2000
      d: 10
      i: 1
      i_clamp: 10000


# Velocity Controllers ---- INSERITI DA ME
arm_j1_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_1
  pid: {p: 8000.0, i: 100, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j2_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_2
  pid: {p: 8000.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j3_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_3
  pid: {p: 8000.0, i: 10, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j4_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_4
  pid: {p: 8000.0, i: 10, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j5_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_5
  pid: {p: 3000.0, i: 5, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j6_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_6
  pid: {p: 500.0, i: 1, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

arm_j7_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: iiwa_joint_7
  pid: {p: 100.0, i: 1, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

gripper_left_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: gripper_left_joint
  pid: {p: 10.0, i: 1, d: 100.0, i_clamp_min: -1, i_clamp_max: 1}

gripper_right_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: gripper_right_joint
  pid: {p: 10.0, i: 1, d: 100.0, i_clamp_min: -1, i_clamp_max: 1}

iiwa_velocity_controller:
  type: effort_controllers/JointGroupEffortController
  #type: effort_controllers/JointVelocityController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 8000
      d: 100
      i: 100
      i_clamp: 10000
    iiwa_joint_2:
      p: 8000
      d: 100
      i: 100
      i_clamp: 10000
    iiwa_joint_3:
      p: 8000
      d: 100
      i: 10
      i_clamp: 10000
    iiwa_joint_4:
      p: 8000
      d: 100
      i: 10
      i_clamp: 10000
    iiwa_joint_5:
      p: 3000
      d: 100
      i: 5
      i_clamp: 10000
    iiwa_joint_6:
      p: 500
      d: 100
      i: 1
      i_clamp: 10000
    iiwa_joint_7:
      p: 100
      d: 100
      i: 1
      i_clamp: 1      
  
grasp_velocity_controller:
  type: effort_controllers/JointVelocityController
  joints:
    - gripper_left_joint
    - gripper_right_joint
  gains:
    gripper_left_joint:
      p: 2000
      d: 10
      i: 1
      i_clamp: 10000
    gripper_right_joint:
      p: 2000
      d: 10
      i: 1
      i_clamp: 10000