controller_list:
  - name: fake_iiwa_arm_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_gripper_controller
    joints:
      - gripper_left_joint
      - gripper_right_joint
initial:  # Define initial robot poses.
  - group: iiwa_arm
    pose: neutral_pose